(function(){function h(){var a;isNaN(a=parseFloat($("#money").val().replace(/,/gi,"")))&&(a=0);var b=Math.ceil(100*(7.5-a/14E6))/100;6.4>b&&(b=6.4);var c=1E4*Math.floor(a/(6E3*b)),d=10*Math.floor(1E4*Math.floor(a/(1E4*b))/(1E3*parseFloat($("#category").val()))),b=Math.round(100*(7.5-b)/7.5)+"%";$("#views").val(addComma(c));$("#discount").val(b);$("#clicks").val(addComma(d));1E3>a||$("#money").val(addComma(a))}function l(){var a="",b=parseFloat($("#diamond_weight").val());if(0<b){$.each(diamonds,function(d,
c){var e=parseFloat(c);e<=b&&6>b&&(a=e)});if(a){tmp="#dia"+a+"_"+$("#diamond_color").val()+"_"+$("#diamond_clarity").val();tmp=tmp.replace(/\./gi,"p");var c=parseInt($(tmp).text().replace(/,/gi,""));0<c&&(c=c*b*1E4*parseInt($("#diamond_number").val()))}0<c?$("#diamond_price").text(addComma(Math.round(c))):$("#diamond_price").text("قیمت یافت نشد")}}function k(){var a,b="even";$(".colors").each(function(){$(this).css("border-left",$(this).val()+" solid 20px")});a='<style type="text/css">';var c=$("#width_perc").val()?
$("#width_perc").val()+"%":$("#width_px").val()+"px";if($("#border-width").val())var d="padding:"+$("#border-padding").val()+"px;direction:rtl;border:"+$("#border-width").val()+"px solid "+$("#border-color").val()+";";a+="#mazanex table,#mazanex td,#mazanex th,#mazanex tr{padding:0;margin:0;border:0;white-space:nowrap;}";a+="#mazanex .mxv a{display:block;}";var g=$("#height_px").val()?"height:"+$("#height_px").val()+"px;":"";a=a+"#mazanex{display:none;width:"+c+";overflow:auto;"+g+"}#mazanex table{margin:0;"+
d+"}";g=$("#td-padding").val()?$("#td-padding").val():5;a=a+"#mazanex td,#mazanex th{padding:"+g+"px;direction: rtl;text-align:right;}";$("#time-color").val()&&(d="color:"+$("#time-color").val()+";");$("#time-size").val()&&(d=d+"size:"+$("#time-size").val()+"px;");d&&(a=a+"#mazanex #mx_update,#mazanex #mx_update {"+d+"}");a=a+"#mazanex table{width:"+c+";margin:0;"+d+"}";$("#header-backcolor").val()&&(d="background-color:"+$("#header-backcolor").val()+";");a=a+"#mazanex th,#mazanex th a{font-size:"+
$("#font_header").val()+"px;color:"+$("#head-color").val()+";"+d+"}";a+="#mazanex th a{padding:0;margin:0;text-decoration:none;background:none;}";a=a+"#mazanex td{font-size:"+$("#font_size").val()+"px;color:"+$("#font-color").val()+";}";a=a+"#mazanex .odd{background-color:"+$("#price-title-color").val()+";}#mazanex .odd td{font-size:"+$("#price-title-size").val()+"px;}";a=a+"#mazanex .even{background-color:"+$("#price-color").val()+";}#mazanex .even td{font-size:"+$("#price-size").val()+"px;}";a=
a+"#mazanex .pos{color:"+$("#pos").val()+";}#mazanex .neg{color:"+$("#neg").val()+";}#mazanex .same{color:"+$("#same").val()+";}";a+="</style>";a+='<div id="mazanex">';if("h"==$("input:radio[name=type]:checked").val())a+='<table><tr><th><a href="http://www.mazanex.com" id="mx_lnk">نرخ طلا و ارز</a></th><th>تغییر</th></tr>',$("#currencies input").each(function(){$(this).prop("checked")&&(a=a+'<tr class="odd"><td colspan="2">'+$(this).parent().text()+"</td></tr>",a=a+'<tr class="even"><td id="v'+$(this).attr("id")+
'"></td><td id="c'+$(this).attr("id")+'"></td></tr>')}),a+='</table><span id="mx_update"></span></div>';else{var e,f;a+='<table class="mxv">';e='<th><a href="http://www.mazanex.com" id="mx_lnk">نرخ طلا و ارز</a></th>';f='<td class="'+b+'" id="mx_update"></td>';$("#currencies input").each(function(){$(this).prop("checked")&&(b="odd"==b?"even":"odd",e=e+"<th>"+$(this).parent().text()+"</th>",f=f+'<td class="'+b+'"> <span id="v'+$(this).attr("id")+'"></span><div id="c'+$(this).attr("id")+'"></div></td>')});
a=a+"<tr>"+e+"</tr>";a=a+"<tr>"+f+"</tr>";a+="</table></div>"}$("#code").val(a).trigger("change")}$(function(){void 0!=$("#money").val()&&h();$("#container").delegate("#ads input,#ads select","keyup change",function(){h()})});$(function(){var a;$("#container").delegate("#archive #archive_get","click",function(b){a=$("#result").html();b.preventDefault();var c=!0;$("#archive select").each(function(){0==$(this).val()&&(c&&alert("لطفا مقادیر تاریخ و نرخ را به طور کامل انتخاب نمایید."),c=!1)});c&&$.post("archive.php",
$("input,select").serialize(),function(a){a=a.split("|");$("#remaining").html(a[1]);$("#result").html(a[0])})});$("#container").delegate("#archive select","change",function(){$("#result").html(a)})});$(function(){$("#container").delegate("#diamond input,#diamond select","keyup change",function(){l()})});$(function(){$("#container").delegate(".tools","change keyup",function(){k()}).delegate("#code","change keyup",function(){$("#preview").html($("#code").val());mx_run()});k()})})();
