function e(a){if(!f){2E8<g()-h&&(j("e/2days"),location.reload(!0));var b=g()-k-1E3*pg_countdown;if(0>b&&!a)return m(5);if(!n&&g()-p>3E3*pg_countdown)return is_active=0,g()-p<4E3*pg_countdown&&j("e/inact"),m(15*pg_countdown);is_active=1;if(q)return m(5);var c=b>1500*pg_countdown?"f":"s";a&&(c="f");var d=$("#type").val();a="/ajax/"+d+c+".json?"+k;q=1;return $.ajax({url:a,type:"GET",timeout:7E3,dataType:"JSON"}).done(function(a){e.a=0;$(".notice .failed").remove();$.each(a,function(a,b){$("."+a).each(function(){var c=
$(this);if("t"==a.charAt(0))c.data("time",b);else if(c.text()!=b){if("c"==a.charAt(0)){if(-1!=b.indexOf("-"))var d="neg";else/([1-9]+)/.test(b)&&(d="pos");c.removeClass("neg pos").addClass(d)}"s"==a.charAt(0)&&c.parent().is("tr")&&(tmp=r(b)<r(c.text())?"chdn":"chup",c.parent().addClass(tmp),"function"==typeof price_update&&price_update(c));c.html(b)}})});setTimeout(function(){$(".chdn,.chup").removeClass("chup chdn")},4E3);"function"==typeof s&&t()}).fail(function(a,b){e.a=e.a+1||0;0==e.a%30&&j("f/"+
b);$(".notice").html("<div class='failed'>"+l.d+"</div>")}).always(function(){q=0}).done(function(a){k=g();a.pg_countdown&&(pg_countdown=a.pg_countdown);$(".dynamic").data("time",pg_countdown);a.rev&&_rev!=a.rev&&location.reload(!0);if("s"!=c||1>--u)"s"==c&&(u=5),j(d+v+"/"+c);m(pg_countdown)}).fail(function(){m(5)}).always(function(){$(".dynamic").fadeIn()})}}function r(a){if(void 0!=a){a=a.replace(/,/gi,"");var b=/([.,0-9]+)/;if(b.test(a))return b.exec(a)[0]}return""}
function g(){return(new Date).getTime()}function j(a){_gaq.push(["_trackPageview",a])}function m(a){clearTimeout(w);w=setTimeout(e,1E3*a)}function x(){$(".counter").each(function(){var a=parseInt($(this).data("time")),a=$(this).hasClass("dynamic")?a?a-1:0:a+1;$(this).data("time",a).find("span").html(y(a))})}function y(a){var b="",c;if(c=Math.floor(a/86400))b=c+l.e+l.b,a-=86400*c;if(c=Math.floor(a/3600))b=b+c+l.f+l.b,a-=3600*c;if(c=Math.floor(a/60))b=b+c+l.g+l.c,a-=60*c;return b+a+l.h}
function z(a){var b,c;b=(a+"").split(".");a=b[0];b=1<b.length?"."+b[1]:"";for(c=/(\d+)(\d{3})/;c.test(a);)a=a.replace(c,"$1,$2");return a+b}function s(){t()}function t(){var a,b=r($("#gld .act").val());if(0<b){a=b;var c=$("#gld .act").data("t"),d=r($(".s3_3:first").html());a=c?b*c:b/d;$("#gld input:not(.act)").each(function(){var b=$(this).data("t");b?$(this).val(z(Math.round(1E4*(a/b))/1E4)):$(this).val(z(100*Math.round(a*d/100)))});$("#gld .act").val(z(b))}}
l={d:"مشکلی در دریافت اطلاعات وجود دارد. ارتباط اینترنت خود را کنترل نمایید. پس از برقراری ارتباط بارگذاری مجددا به صورت خودکار انجام خواهد شد.",e:" روز ",f:" ساعت ",g:" دقیقه ",h:" ثانیه ",c:" و ",b:"،"};var k=g(),n=1,p,q=0,w,v="",h=g(),u=0,f=!1;
$(function(){is_active=1;$("#type").val()&&($(document).bind("mousemove keydown DOMMouseScroll mousewheel mousedown touchstart touchmove",function(){p=g();n||e()}),$(window).focus(function(){n=1;p=g();e()}).blur(function(){n=0}),setInterval(x,1E3),m(pg_countdown),setTimeout(function(){$(".dynamic").fadeIn()},2E3));$(".xvq").data("q")&&null==A.get("vote_"+$(".xvq").data("q"))&&$(".xv").slideDown();$("#header").delegate("a.manual","click",function(a){$(".dynamic").fadeOut();j("e/forced");a.preventDefault();
e(1)});$("body").delegate(".ad a,.track a","click",function(){j($(this).attr("href"))}).delegate(".chart a","click",function(a){a.preventDefault();$("#chart_box").html('<img src="'+$(this).attr("href").replace(/stamp/,k)+'" />').fadeIn("slow")}).delegate(".ajaxpost","submit",function(a){a.preventDefault();$.post($(this).attr("action"),$(this).serialize(),function(a){$("#container").html(a).fadeTo("slow",1)})}).delegate(".xv a","click",function(a){a.preventDefault();j("v/"+$(".xvq").data("q")+"/"+
$(this).data("a"));A.set("vote_"+$(".xvq").data("q"),1,3E8);$(".xv").slideUp()})});var A={get:function(a){var b;return document.cookie&&(b=document.cookie.match(RegExp(a+"=([^;]+)")))?unescape(b[1]):null},set:function(a,b,c){var d=new Date;d.setTime(d.getTime()+(0==c?2E10:c));return document.cookie=a+"="+escape(b)+"; path=/; expires="+(""!=b?d.toGMTString():-1)}};window.addComma=z;var B=document.createElement("script");B.type="text/javascript";B.async=!0;
B.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var C=document.getElementsByTagName("script")[0];C.parentNode.insertBefore(B,C);
