(function(){function e(a){if(!y){2E8<d()-z&&(f("e/2days"),location.reload(!0));var b=d()-h-1E3*pg_countdown;if(0>b&&!a)return g(5);if(!k&&d()-m>3E3*pg_countdown)return is_active=0,d()-m<4E3*pg_countdown&&f("e/inact"),g(15*pg_countdown);is_active=1;if(r)return g(5);var c=b>1500*pg_countdown?"f":"s";a&&(c="f");var s=$("#type").val();return A("/ajax/"+s+c+".json?"+h).done(function(a){h=d();a.pg_countdown&&(pg_countdown=a.pg_countdown);$(".dynamic").data("time",pg_countdown);a.rev&&_rev!=a.rev&&location.reload(!0);
if("s"!=c||1>--t)"s"==c&&(t=5),f(s+B+"/"+c);g(pg_countdown)}).fail(function(){g(5)}).always(function(){$(".dynamic").fadeIn()})}}function A(a){var b;r=1;return $.ajax({url:a,type:"GET",timeout:7E3,dataType:"JSON"}).done(function(a){e.a=0;$(".notice .failed").remove();$.each(a,function(a,c){"d"==a.charAt(0)?(b=a.split("-"),$("."+b[0]).data(b[1],c)):$("."+a).each(function(){var d=$(this);if("t"==a.charAt(0))d.data("time",c);else if(d.text()!=c){if("c"==a.charAt(0)){if(-1!=c.indexOf("-"))var e="neg";
else/([1-9]+)/.test(c)&&(e="pos");d.removeClass("neg pos").addClass(e)}"s"==a.charAt(0)&&d.parent().is("tr")&&(b=n(c)<n(d.text())?"chdn":"chup",d.parent().addClass(b),"function"==typeof price_update&&price_update(d));d.html(c)}})});setTimeout(function(){$(".chdn,.chup").removeClass("chup chdn")},4E3);"function"==typeof C&&u()}).fail(function(a,b){e.a=e.a+1||0;0==e.a%30&&f("f/"+b);$(".notice").html("<div class='failed'>"+l.d+"</div>")}).always(function(){r=0})}function n(a){if(void 0!=a){a=a.replace(/,/gi,
"");var b=/([.,0-9]+)/;if(b.test(a))return b.exec(a)[0]}return""}function d(){return(new Date).getTime()}function f(a){_gaq.push(["_trackPageview",a])}function g(a){clearTimeout(v);v=setTimeout(e,1E3*a)}function D(){$(".counter").each(function(){var a=parseInt($(this).data("time")),a=$(this).hasClass("dynamic")?a?a-1:0:a+1;$(this).data("time",a).find("span").html(E(a))})}function E(a){var b="",c;if(c=Math.floor(a/86400))b=c+l.e+l.b,a-=86400*c;if(c=Math.floor(a/3600))b=b+c+l.f+l.b,a-=3600*c;if(c=Math.floor(a/
60))b=b+c+l.g+l.c,a-=60*c;return b+a+l.h}function p(a){var b,c;b=(a+"").split(".");a=b[0];b=1<b.length?"."+b[1]:"";for(c=/(\d+)(\d{3})/;c.test(a);)a=a.replace(c,"$1,$2");return a+b}function C(){u()}function u(){var a,b=n($("#gld .act").val());if(0<b){a=b;var c=$("#gld .act").data("t"),d=n($(".s3_3:first").html());a=c?b*c:b/d;$("#gld input:not(.act)").each(function(){var b=$(this).data("t");b?$(this).val(p(Math.round(a/b*1E4)/1E4)):$(this).val(p(100*Math.round(a*d/100)))});$("#gld .act").val(p(b))}}
l={d:"مشکلی در دریافت اطلاعات وجود دارد. ارتباط اینترنت خود را کنترل نمایید. پس از برقراری ارتباط بارگذاری مجددا به صورت خودکار انجام خواهد شد.",e:" روز ",f:" ساعت ",g:" دقیقه ",h:" ثانیه ",c:" و ",b:"،"};var h=d(),k=1,m,r=0,v,B="",z=d(),t=0,y=!1;$(function(){is_active=1;$("#type").val()&&($(document).bind("mousemove keydown DOMMouseScroll mousewheel mousedown touchstart touchmove",function(){m=d();k||e()}),$(window).focus(function(){k=1;m=d();e()}).blur(function(){k=0}),setInterval(D,1E3),g(pg_countdown),
setTimeout(function(){$(".dynamic").fadeIn()},2E3));$(".xvq").data("q")&&null==w.get("vote_"+$(".xvq").data("q"))&&$(".xv").slideDown();$("#header").delegate("a.manual","click",function(a){$(".dynamic").fadeOut();f("e/forced");a.preventDefault();e(1)});$("body").delegate(".track a","click",function(){f($(this).attr("href"))}).delegate(".chart a","click",function(a){0!=$("#chart_box").length&&(a.preventDefault(),$("#chart_box").html('<img src="'+$(this).attr("href").replace(/stamp/,h)+'" />').fadeIn("slow"))}).delegate(".ajaxpost",
"submit",function(a){a.preventDefault();$.post($(this).attr("action"),$(this).serialize(),function(a){$("#container").html(a).fadeTo("slow",1)})}).delegate(".xv a","click",function(a){a.preventDefault();f("v/"+$(".xvq").data("q")+"/"+$(this).data("a"));w.set("vote_"+$(".xvq").data("q"),1,3E8);$(".xv").slideUp()}).delegate(".ad a","click",function(){var a=$(this).attr("href"),b=$(this).data("id");b&&($(this).data("url")?a=$(this).data("url"):$(this).data("url",a));f(a);b&&$(this).attr("href","//re.aclick.com/"+
b+a)})});var w={get:function(a){var b;return document.cookie&&(b=document.cookie.match(RegExp(a+"=([^;]+)")))?unescape(b[1]):null},set:function(a,b,c){var d=new Date;d.setTime(d.getTime()+(0==c?2E10:c));return document.cookie=a+"="+escape(b)+"; path=/; expires="+(""!=b?d.toGMTString():-1)}};window.addComma=p;var q=document.createElement("script");q.type="text/javascript";q.async=!0;q.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var x=document.getElementsByTagName("script")[0];
x.parentNode.insertBefore(q,x)})();
